---
deployment:
  tasks:
    - echo "DEPLOY WORKING"

    - export DEPLOYPATH=/home/vjxzcyjr/charlyhb
    - echo "DEPLOYPATH: $DEPLOYPATH"
    - cd $DEPLOYPATH

    - echo "turning artisanDOWN"
    - php artisan down || true

    - echo "clearing cache"
    - php artisan config:clear
    - php artisan cache:clear

    - echo "migrating"
    - php artisan migrate --force || true

    - echo "caching"
    - php artisan config:cache
    - php artisan route:cache

    - echo "turning artisanUP"
    - php artisan up || true